[package]
name = "aldrin-gen"
description = "Aldrin code generator."
version = "0.13.0"

categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anstream = { workspace = true }
anstyle = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
colorchoice-clap = { workspace = true }
diffy = { workspace = true }
terminal_size = { workspace = true }

[dependencies.aldrin-codegen]
version = "0.13.0"
path = "../codegen"
default-features = false
features = ["rust"]

[dependencies.aldrin-parser]
version = "0.13.0"
path = "../parser"
default-features = false
